name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente ou em cada push (opcional, pode ser comentado)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Usa o token nativo das actions (não precisa configurar secret)
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configurações básicas (Removidas seções poluídas)
          user: andsantosx
          template: classic
          base: header
          config_timezone: America/Sao_Paulo
          config_transparent: yes
          
          # Plugin Isocalendar (Calendário 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_main: yes
          
          # Ordem de exibição dos painéis
          config_order: base.header, isocalendar
